version: '3.3'
services:
  db:
    image: postgres
    restart: always
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - 15434:5432
    environment:
      - POSTGRES_USER=service_declaration
      - POSTGRES_PASSWORD=service_declaration